package com.boardinghouse.dto;

import com.boardinghouse.entity.HousekeepingTask;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class HousekeepingTaskDto {
    private Long id;
    private Long roomId;
    private String roomCode;
    private Long boardingHouseId;
    private String boardingHouseName;
    private Long contractId;
    private Long assignedToId;
    private String assignedToName;
    private String title;
    private String notes;
    private HousekeepingTask.TaskStatus status;
    private HousekeepingTask.Priority priority;
    private LocalDate scheduledDate;
    private LocalDateTime startedAt;
    private LocalDateTime completedAt;
    private LocalDateTime createdAt;
    private Boolean autoGenerated;

    public HousekeepingTaskDto() {}

    // Getters & Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public Long getRoomId() { return roomId; }
    public void setRoomId(Long roomId) { this.roomId = roomId; }
    public String getRoomCode() { return roomCode; }
    public void setRoomCode(String roomCode) { this.roomCode = roomCode; }
    public Long getBoardingHouseId() { return boardingHouseId; }
    public void setBoardingHouseId(Long boardingHouseId) { this.boardingHouseId = boardingHouseId; }
    public String getBoardingHouseName() { return boardingHouseName; }
    public void setBoardingHouseName(String boardingHouseName) { this.boardingHouseName = boardingHouseName; }
    public Long getContractId() { return contractId; }
    public void setContractId(Long contractId) { this.contractId = contractId; }
    public Long getAssignedToId() { return assignedToId; }
    public void setAssignedToId(Long assignedToId) { this.assignedToId = assignedToId; }
    public String getAssignedToName() { return assignedToName; }
    public void setAssignedToName(String assignedToName) { this.assignedToName = assignedToName; }
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }
    public String getNotes() { return notes; }
    public void setNotes(String notes) { this.notes = notes; }
    public HousekeepingTask.TaskStatus getStatus() { return status; }
    public void setStatus(HousekeepingTask.TaskStatus status) { this.status = status; }
    public HousekeepingTask.Priority getPriority() { return priority; }
    public void setPriority(HousekeepingTask.Priority priority) { this.priority = priority; }
    public LocalDate getScheduledDate() { return scheduledDate; }
    public void setScheduledDate(LocalDate scheduledDate) { this.scheduledDate = scheduledDate; }
    public LocalDateTime getStartedAt() { return startedAt; }
    public void setStartedAt(LocalDateTime startedAt) { this.startedAt = startedAt; }
    public LocalDateTime getCompletedAt() { return completedAt; }
    public void setCompletedAt(LocalDateTime completedAt) { this.completedAt = completedAt; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    public Boolean getAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(Boolean autoGenerated) { this.autoGenerated = autoGenerated; }
}
