import { useEffect, useState, useMemo } from 'react'
import api from '../../services/api'
import { useProperty } from '../../context/PropertyContext'
import { useToast } from '../../context/ToastContext'
import {
  Plus, CheckCircle2, Clock, PlayCircle, SkipForward,
  Trash2, X, ChevronDown, User, Calendar, Home, Filter,
  AlertTriangle, Zap, ArrowUpDown, Search, RefreshCw
} from 'lucide-react'

const fmt = (d) => d ? new Date(d + 'T00:00:00').toLocaleDateString('vi-VN') : '—'
const fmtTime = (dt) => dt ? new Date(dt).toLocaleString('vi-VN', { hour: '2-digit', minute: '2-digit', day: '2-digit', month: '2-digit' }) : '—'

const STATUS_CFG = {
  PENDING:     { label: 'Chờ dọn',    color: 'amber',   icon: Clock,         bg: 'bg-amber-50',   text: 'text-amber-700',   border: 'border-amber-200'  },
  IN_PROGRESS: { label: 'Đang dọn',   color: 'blue',    icon: PlayCircle,    bg: 'bg-blue-50',    text: 'text-blue-700',    border: 'border-blue-200'   },
  DONE:        { label: 'Xong',        color: 'emerald', icon: CheckCircle2,  bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200'},
  SKIPPED:     { label: 'Bỏ qua',     color: 'slate',   icon: SkipForward,   bg: 'bg-slate-50',   text: 'text-slate-500',   border: 'border-slate-200'  },
}

const PRIORITY_CFG = {
  LOW:    { label: 'Thấp',   color: 'text-slate-400' },
  NORMAL: { label: 'Thường', color: 'text-blue-500'  },
  HIGH:   { label: 'Cao',    color: 'text-orange-500'},
  URGENT: { label: 'Khẩn',  color: 'text-red-600 font-black' },
}

const inputCls = 'w-full px-3 py-2 border border-slate-200 rounded-xl text-sm text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all bg-white'

// ─── Task Card ────────────────────────────────────────────────────────────────
const TaskCard = ({ task, staff, onStatusChange, onDelete, onEdit }) => {
  const cfg = STATUS_CFG[task.status] || STATUS_CFG.PENDING
  const pCfg = PRIORITY_CFG[task.priority] || PRIORITY_CFG.NORMAL
  const StatusIcon = cfg.icon
  const [changing, setChanging] = useState(false)

  const nextStatus = {
    PENDING: 'IN_PROGRESS',
    IN_PROGRESS: 'DONE',
    DONE: null,
    SKIPPED: null,
  }[task.status]

  const nextLabel = { IN_PROGRESS: '▶ Bắt đầu', DONE: '✓ Hoàn thành' }[nextStatus]

  const changeStatus = async (status) => {
    setChanging(true)
    try { await onStatusChange(task.id, status) }
    finally { setChanging(false) }
  }

  return (
    <div className={`bg-white border rounded-2xl shadow-sm hover:shadow-md transition-all duration-200 overflow-hidden
      ${task.status === 'DONE' ? 'opacity-60' : ''}`}
      style={{ animation: 'fadeSlide 0.2s ease both' }}>

      {/* Color bar */}
      <div className={`h-1 w-full ${
        task.status === 'PENDING' ? 'bg-amber-400' :
        task.status === 'IN_PROGRESS' ? 'bg-blue-500' :
        task.status === 'DONE' ? 'bg-emerald-400' : 'bg-slate-200'}`} />

      <div className="p-4">
        {/* Header */}
        <div className="flex items-start justify-between gap-3 mb-3">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap mb-1">
              <span className={`text-[10px] font-black uppercase tracking-widest ${pCfg.color}`}>
                {task.priority === 'URGENT' ? '🚨' : task.priority === 'HIGH' ? '🔴' : ''}
                {pCfg.label}
              </span>
              {task.autoGenerated && (
                <span className="text-[9px] font-black text-violet-600 bg-violet-50 border border-violet-200 px-1.5 py-0.5 rounded-full flex items-center gap-0.5">
                  <Zap className="w-2.5 h-2.5" /> Auto
                </span>
              )}
            </div>
            <h3 className="font-bold text-slate-900 text-sm leading-tight">{task.title}</h3>
          </div>
          <div className="flex gap-1 flex-shrink-0">
            <button onClick={() => onEdit(task)}
              className="w-7 h-7 flex items-center justify-center rounded-lg hover:bg-slate-100 text-slate-400 hover:text-slate-600 transition-all">
              <ChevronDown className="w-3.5 h-3.5" />
            </button>
            <button onClick={() => onDelete(task.id)}
              className="w-7 h-7 flex items-center justify-center rounded-lg hover:bg-red-50 text-slate-400 hover:text-red-500 transition-all">
              <Trash2 className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>

        {/* Info row */}
        <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-slate-500 mb-3">
          <span className="flex items-center gap-1 font-bold text-slate-700">
            <Home className="w-3 h-3" /> {task.roomCode}
          </span>
          <span className="flex items-center gap-1">
            <Calendar className="w-3 h-3" /> {fmt(task.scheduledDate)}
          </span>
          {task.assignedToName && (
            <span className="flex items-center gap-1">
              <User className="w-3 h-3" /> {task.assignedToName}
            </span>
          )}
          {!task.assignedToName && (
            <span className="text-slate-300 italic">Chưa assign</span>
          )}
        </div>

        {task.notes && (
          <p className="text-[11px] text-slate-400 mb-3 bg-slate-50 rounded-lg px-2.5 py-1.5 leading-relaxed">
            {task.notes}
          </p>
        )}

        {/* Timestamps */}
        {(task.startedAt || task.completedAt) && (
          <div className="text-[10px] text-slate-400 mb-3 space-y-0.5">
            {task.startedAt && <p>▶ Bắt đầu: {fmtTime(task.startedAt)}</p>}
            {task.completedAt && <p>✓ Xong: {fmtTime(task.completedAt)}</p>}
          </div>
        )}

        {/* Actions */}
        <div className="flex items-center gap-2 pt-2 border-t border-slate-100">
          <span className={`flex items-center gap-1.5 text-[10px] font-black px-2.5 py-1.5 rounded-full border ${cfg.bg} ${cfg.text} ${cfg.border}`}>
            <StatusIcon className="w-3 h-3" /> {cfg.label}
          </span>
          <div className="flex gap-1.5 ml-auto">
            {nextStatus && (
              <button disabled={changing} onClick={() => changeStatus(nextStatus)}
                className="text-[11px] font-bold px-3 py-1.5 rounded-xl bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-60 transition-all hover:-translate-y-0.5 active:scale-95 shadow-sm shadow-blue-500/20">
                {changing ? '...' : nextLabel}
              </button>
            )}
            {task.status !== 'SKIPPED' && task.status !== 'DONE' && (
              <button onClick={() => changeStatus('SKIPPED')}
                className="text-[11px] font-medium px-3 py-1.5 rounded-xl bg-slate-100 text-slate-500 hover:bg-slate-200 transition-all">
                Bỏ qua
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}

// ─── Modal ────────────────────────────────────────────────────────────────────
const TaskModal = ({ task, rooms, staff, propertyId, onClose, onSave }) => {
  const [form, setForm] = useState({
    roomId: task?.roomId || '',
    assignedToId: task?.assignedToId || '',
    title: task?.title || '🧹 Dọn phòng',
    notes: task?.notes || '',
    status: task?.status || 'PENDING',
    priority: task?.priority || 'NORMAL',
    scheduledDate: task?.scheduledDate || new Date().toISOString().slice(0, 10),
    boardingHouseId: propertyId !== 'ALL' ? parseInt(propertyId) : null,
  })
  const set = k => e => setForm(f => ({ ...f, [k]: e.target.value }))

  const handleSubmit = async (e) => {
    e.preventDefault()
    const payload = { ...form, roomId: parseInt(form.roomId), assignedToId: form.assignedToId ? parseInt(form.assignedToId) : null }
    await onSave(payload)
    onClose()
  }

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4"
      onClick={onClose}>
      <div className="bg-white w-full max-w-md rounded-3xl shadow-2xl overflow-hidden"
        onClick={e => e.stopPropagation()}
        style={{ animation: 'modalPop 0.25s cubic-bezier(0.16,1,0.3,1)' }}>
        <div className="bg-gradient-to-r from-violet-600 to-purple-600 px-6 py-5 flex items-center justify-between">
          <div>
            <h2 className="font-black text-white text-lg">{task ? '✏️ Sửa Task' : '✨ Tạo Task'}</h2>
            <p className="text-white/60 text-xs mt-0.5">Phân công dọn phòng</p>
          </div>
          <button onClick={onClose} className="w-8 h-8 bg-white/20 hover:bg-white/30 rounded-xl flex items-center justify-center transition-all">
            <X className="w-4 h-4 text-white" />
          </button>
        </div>
        <form onSubmit={handleSubmit} className="p-5 space-y-3.5">
          <div>
            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Phòng *</label>
            <select required value={form.roomId} onChange={set('roomId')} className={inputCls + ' mt-1.5'}>
              <option value="">— Chọn phòng —</option>
              {rooms.map(r => <option key={r.id} value={r.id}>{r.code} · {r.boardingHouseName}</option>)}
            </select>
          </div>
          <div>
            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Tiêu đề *</label>
            <input required value={form.title} onChange={set('title')} className={inputCls + ' mt-1.5'} />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Ưu tiên</label>
              <select value={form.priority} onChange={set('priority')} className={inputCls + ' mt-1.5'}>
                <option value="LOW">Thấp</option>
                <option value="NORMAL">Thường</option>
                <option value="HIGH">Cao</option>
                <option value="URGENT">Khẩn</option>
              </select>
            </div>
            <div>
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Ngày dọn *</label>
              <input type="date" required value={form.scheduledDate} onChange={set('scheduledDate')} className={inputCls + ' mt-1.5'} />
            </div>
          </div>
          <div>
            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Assign cho</label>
            <select value={form.assignedToId} onChange={set('assignedToId')} className={inputCls + ' mt-1.5'}>
              <option value="">— Chưa assign —</option>
              {staff.map(s => <option key={s.id} value={s.id}>{s.fullName}</option>)}
            </select>
          </div>
          <div>
            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Ghi chú</label>
            <textarea value={form.notes} onChange={set('notes')} rows={2}
              className={inputCls + ' mt-1.5 resize-none'} placeholder="Chú ý đặc biệt..." />
          </div>
          <div className="flex gap-3 pt-2">
            <button type="button" onClick={onClose}
              className="flex-1 py-2.5 border border-slate-200 rounded-xl text-sm font-bold text-slate-600 hover:bg-slate-50 transition-all">Hủy</button>
            <button type="submit"
              className="flex-1 py-2.5 bg-gradient-to-r from-violet-600 to-purple-600 text-white rounded-xl text-sm font-bold shadow-lg shadow-violet-500/20 hover:-translate-y-0.5 transition-all active:scale-[0.98]">
              {task ? '💾 Lưu' : '✨ Tạo Task'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

// ─── Main Component ───────────────────────────────────────────────────────────
const Housekeeping = () => {
  const { selectedId: propertyId, properties } = useProperty()
  const { showToast } = useToast()
  const [tasks, setTasks] = useState([])
  const [rooms, setRooms] = useState([])
  const [staff, setStaff] = useState([])
  const [loading, setLoading] = useState(true)
  const [showModal, setShowModal] = useState(false)
  const [editTask, setEditTask] = useState(null)
  const [filterStatus, setFilterStatus] = useState('ALL')
  const [filterDate, setFilterDate] = useState('')
  const [search, setSearch] = useState('')

  useEffect(() => { fetchAll() }, [propertyId])

  const fetchAll = async () => {
    if (propertyId === 'ALL') { setTasks([]); setLoading(false); return }
    setLoading(true)
    try {
      const [tr, rr, ur] = await Promise.all([
        api.get(`/housekeeping?boardingHouseId=${propertyId}`),
        api.get(`/rooms?boardingHouseId=${propertyId}`),
        api.get('/users/admin/all'),
      ])
      setTasks(tr.data)
      setRooms(rr.data)
      setStaff(ur.data.filter(u => !u.roles?.includes('TENANT')))
    } catch (e) { console.error(e) }
    finally { setLoading(false) }
  }

  const handleStatusChange = async (id, status) => {
    try {
      await api.patch(`/housekeeping/${id}/status`, { status })
      setTasks(prev => prev.map(t => t.id === id ? { ...t, status } : t))
      showToast('Đã cập nhật trạng thái', 'success')
    } catch (e) { showToast('Lỗi', 'error') }
  }

  const handleSave = async (data) => {
    try {
      if (editTask) {
        const r = await api.put(`/housekeeping/${editTask.id}`, data)
        setTasks(prev => prev.map(t => t.id === editTask.id ? r.data : t))
        showToast('Đã cập nhật task', 'success')
      } else {
        const r = await api.post('/housekeeping', data)
        setTasks(prev => [...prev, r.data])
        showToast('Đã tạo task', 'success')
      }
    } catch (e) { showToast(e.response?.data?.message || 'Lỗi', 'error') }
  }

  const handleDelete = async (id) => {
    if (!confirm('Xóa task này?')) return
    try {
      await api.delete(`/housekeeping/${id}`)
      setTasks(prev => prev.filter(t => t.id !== id))
      showToast('Đã xóa', 'success')
    } catch (e) { showToast('Lỗi xóa', 'error') }
  }

  const filtered = useMemo(() => {
    let f = [...tasks]
    if (filterStatus !== 'ALL') f = f.filter(t => t.status === filterStatus)
    if (filterDate) f = f.filter(t => t.scheduledDate === filterDate)
    if (search) {
      const q = search.toLowerCase()
      f = f.filter(t => [t.title, t.roomCode, t.assignedToName, t.notes].some(v => v?.toLowerCase().includes(q)))
    }
    // Sort: URGENT first, then by date
    f.sort((a, b) => {
      const pOrder = { URGENT: 0, HIGH: 1, NORMAL: 2, LOW: 3 }
      if (a.status === 'DONE' && b.status !== 'DONE') return 1
      if (b.status === 'DONE' && a.status !== 'DONE') return -1
      const pDiff = (pOrder[a.priority] || 2) - (pOrder[b.priority] || 2)
      if (pDiff !== 0) return pDiff
      return (a.scheduledDate || '').localeCompare(b.scheduledDate || '')
    })
    return f
  }, [tasks, filterStatus, filterDate, search])

  // Stats
  const stats = {
    total: tasks.length,
    pending: tasks.filter(t => t.status === 'PENDING').length,
    inProgress: tasks.filter(t => t.status === 'IN_PROGRESS').length,
    done: tasks.filter(t => t.status === 'DONE').length,
    urgent: tasks.filter(t => t.priority === 'URGENT' && t.status !== 'DONE').length,
  }

  if (propertyId === 'ALL') return (
    <div className="flex flex-col items-center justify-center py-24 text-slate-400">
      <Home className="w-12 h-12 mb-3 opacity-30" />
      <p className="font-bold text-slate-600">Chọn một nhà trọ để xem Housekeeping</p>
      <p className="text-sm mt-1">Dùng bộ lọc nhà trọ ở góc trên phải</p>
    </div>
  )

  return (
    <div className="space-y-5">
      <style>{`
        @keyframes fadeSlide { from { opacity:0; transform:translateY(8px) } to { opacity:1; transform:translateY(0) } }
        @keyframes modalPop { from { opacity:0; transform:scale(0.93) translateY(8px) } to { opacity:1; transform:scale(1) translateY(0) } }
      `}</style>

      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-xl font-extrabold text-slate-900 flex items-center gap-2">
            🧹 Housekeeping
          </h1>
          <p className="text-slate-500 text-xs mt-0.5">
            {properties.find(p => p.id == propertyId)?.name} · {filtered.length} tasks
          </p>
        </div>
        <div className="flex gap-2">
          <button onClick={fetchAll}
            className="w-9 h-9 flex items-center justify-center border border-slate-200 rounded-xl text-slate-500 hover:bg-slate-50 transition-all">
            <RefreshCw className="w-4 h-4" />
          </button>
          <button onClick={() => { setEditTask(null); setShowModal(true) }}
            className="flex items-center gap-2 px-4 py-2 bg-violet-600 text-white rounded-xl font-bold text-sm hover:bg-violet-700 shadow-lg shadow-violet-500/20 transition-all hover:-translate-y-0.5">
            <Plus className="w-4 h-4" /> Tạo Task
          </button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
        {[
          { label: 'Tổng', value: stats.total, color: 'slate' },
          { label: 'Chờ dọn', value: stats.pending, color: 'amber' },
          { label: 'Đang dọn', value: stats.inProgress, color: 'blue' },
          { label: 'Xong', value: stats.done, color: 'emerald' },
          { label: '🚨 Khẩn', value: stats.urgent, color: 'red' },
        ].map(s => (
          <div key={s.label} className={`rounded-2xl p-3.5 border bg-${s.color}-50 border-${s.color}-200`}>
            <p className={`text-[10px] font-black uppercase tracking-wide text-${s.color}-600`}>{s.label}</p>
            <p className={`text-2xl font-black mt-1 text-${s.color}-700`}>{s.value}</p>
          </div>
        ))}
      </div>

      {/* Filters */}
      <div className="bg-white rounded-2xl border border-slate-200 p-4 flex flex-col sm:flex-row gap-3">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400" />
          <input value={search} onChange={e => setSearch(e.target.value)}
            placeholder="Tìm phòng, tên, ghi chú..."
            className="w-full pl-9 pr-3 py-2 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-violet-500" />
        </div>
        <select value={filterStatus} onChange={e => setFilterStatus(e.target.value)}
          className="px-3 py-2 border border-slate-200 rounded-xl text-sm font-medium focus:outline-none focus:ring-2 focus:ring-violet-500 appearance-none min-w-[130px]">
          <option value="ALL">Tất cả trạng thái</option>
          {Object.entries(STATUS_CFG).map(([k, v]) => <option key={k} value={k}>{v.label}</option>)}
        </select>
        <input type="date" value={filterDate} onChange={e => setFilterDate(e.target.value)}
          className="px-3 py-2 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-violet-500" />
        {filterDate && (
          <button onClick={() => setFilterDate('')}
            className="px-3 py-2 border border-slate-200 rounded-xl text-sm text-slate-500 hover:bg-slate-50">
            Xóa filter
          </button>
        )}
      </div>

      {/* Task Grid */}
      {loading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {[1,2,3,4,5,6].map(i => (
            <div key={i} className="h-48 bg-slate-100 rounded-2xl animate-pulse" />
          ))}
        </div>
      ) : filtered.length === 0 ? (
        <div className="bg-white border border-slate-200 rounded-2xl py-20 text-center">
          <CheckCircle2 className="w-12 h-12 mx-auto mb-3 text-emerald-300" />
          <p className="font-bold text-slate-600">Không có task nào</p>
          <p className="text-sm text-slate-400 mt-1">Tất cả phòng đã sẵn sàng đón khách! 🎉</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {filtered.map(task => (
            <TaskCard key={task.id} task={task} staff={staff}
              onStatusChange={handleStatusChange}
              onDelete={handleDelete}
              onEdit={t => { setEditTask(t); setShowModal(true) }} />
          ))}
        </div>
      )}

      {showModal && (
        <TaskModal task={editTask} rooms={rooms} staff={staff} propertyId={propertyId}
          onClose={() => { setShowModal(false); setEditTask(null) }}
          onSave={handleSave} />
      )}
    </div>
  )
}

export default Housekeeping
