package com.boardinghouse.service;

import com.boardinghouse.dto.HousekeepingTaskDto;
import com.boardinghouse.entity.*;
import com.boardinghouse.exception.ResourceNotFoundException;
import com.boardinghouse.repository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Service
@Transactional
public class HousekeepingService {

    private final HousekeepingTaskRepository taskRepo;
    private final RoomRepository roomRepo;
    private final ContractRepository contractRepo;
    private final UserRepository userRepo;
    private final BoardingHouseRepository boardingHouseRepo;

    public HousekeepingService(HousekeepingTaskRepository taskRepo,
                               RoomRepository roomRepo,
                               ContractRepository contractRepo,
                               UserRepository userRepo,
                               BoardingHouseRepository boardingHouseRepo) {
        this.taskRepo = taskRepo;
        this.roomRepo = roomRepo;
        this.contractRepo = contractRepo;
        this.userRepo = userRepo;
        this.boardingHouseRepo = boardingHouseRepo;
    }

    // ── Read ──────────────────────────────────────────────────────────────────

    public List<HousekeepingTaskDto> getByBoardingHouse(Long bhId) {
        return taskRepo.findByBoardingHouseId(bhId).stream().map(this::toDto).collect(Collectors.toList());
    }

    public List<HousekeepingTaskDto> getActive(Long bhId) {
        return taskRepo.findActiveTasks(bhId).stream().map(this::toDto).collect(Collectors.toList());
    }

    public List<HousekeepingTaskDto> getByRoom(Long roomId) {
        return taskRepo.findByRoomIdOrderByScheduledDateDesc(roomId).stream().map(this::toDto).collect(Collectors.toList());
    }

    public HousekeepingTaskDto getById(Long id) {
        return toDto(taskRepo.findById(id).orElseThrow(() -> new ResourceNotFoundException("Task not found: " + id)));
    }

    // ── Create ────────────────────────────────────────────────────────────────

    public HousekeepingTaskDto create(HousekeepingTaskDto dto) {
        HousekeepingTask task = buildFromDto(dto, new HousekeepingTask());
        return toDto(taskRepo.save(task));
    }

    /**
     * Called automatically when a guest checks out (contract status COMPLETED / roomReleased = true).
     * Creates a PENDING cleaning task for today, only if one doesn't already exist for this contract.
     */
    public HousekeepingTaskDto createCheckoutTask(Long contractId) {
        Contract contract = contractRepo.findById(contractId)
                .orElseThrow(() -> new ResourceNotFoundException("Contract not found: " + contractId));

        // Idempotent: skip if already created
        if (taskRepo.existsByContractIdAndStatus(contractId, HousekeepingTask.TaskStatus.PENDING)) {
            return null;
        }

        HousekeepingTask task = new HousekeepingTask();
        task.setRoom(contract.getRoom());
        task.setContract(contract);
        task.setTitle("🧹 Dọn phòng sau checkout — " + contract.getRoom().getCode());
        task.setNotes("Khách: " + contract.getMainTenant().getFullName()
                + " · Check-out: " + contract.getEndDate());
        task.setStatus(HousekeepingTask.TaskStatus.PENDING);
        task.setPriority(HousekeepingTask.Priority.HIGH);
        task.setScheduledDate(LocalDate.now());
        task.setAutoGenerated(true);

        return toDto(taskRepo.save(task));
    }

    // ── Update ────────────────────────────────────────────────────────────────

    public HousekeepingTaskDto update(Long id, HousekeepingTaskDto dto) {
        HousekeepingTask task = taskRepo.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Task not found: " + id));
        return toDto(taskRepo.save(buildFromDto(dto, task)));
    }

    public HousekeepingTaskDto updateStatus(Long id, HousekeepingTask.TaskStatus newStatus) {
        HousekeepingTask task = taskRepo.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Task not found: " + id));
        task.setStatus(newStatus);
        if (newStatus == HousekeepingTask.TaskStatus.IN_PROGRESS && task.getStartedAt() == null) {
            task.setStartedAt(LocalDateTime.now());
        }
        if (newStatus == HousekeepingTask.TaskStatus.DONE && task.getCompletedAt() == null) {
            task.setCompletedAt(LocalDateTime.now());
        }
        return toDto(taskRepo.save(task));
    }

    // ── Delete ────────────────────────────────────────────────────────────────

    public void delete(Long id) {
        if (!taskRepo.existsById(id)) throw new ResourceNotFoundException("Task not found: " + id);
        taskRepo.deleteById(id);
    }

    // ── Mapping ───────────────────────────────────────────────────────────────

    private HousekeepingTask buildFromDto(HousekeepingTaskDto dto, HousekeepingTask task) {
        if (dto.getRoomId() != null) {
            task.setRoom(roomRepo.findById(dto.getRoomId())
                    .orElseThrow(() -> new ResourceNotFoundException("Room not found: " + dto.getRoomId())));
        }
        if (dto.getContractId() != null) {
            contractRepo.findById(dto.getContractId()).ifPresent(task::setContract);
        }
        if (dto.getAssignedToId() != null) {
            userRepo.findById(dto.getAssignedToId()).ifPresent(task::setAssignedTo);
        } else {
            task.setAssignedTo(null);
        }
        if (dto.getTitle() != null) task.setTitle(dto.getTitle());
        if (dto.getNotes() != null) task.setNotes(dto.getNotes());
        if (dto.getStatus() != null) task.setStatus(dto.getStatus());
        if (dto.getPriority() != null) task.setPriority(dto.getPriority());
        if (dto.getScheduledDate() != null) task.setScheduledDate(dto.getScheduledDate());
        if (dto.getAutoGenerated() != null) task.setAutoGenerated(dto.getAutoGenerated());
        return task;
    }

    private HousekeepingTaskDto toDto(HousekeepingTask t) {
        HousekeepingTaskDto dto = new HousekeepingTaskDto();
        dto.setId(t.getId());
        dto.setTitle(t.getTitle());
        dto.setNotes(t.getNotes());
        dto.setStatus(t.getStatus());
        dto.setPriority(t.getPriority());
        dto.setScheduledDate(t.getScheduledDate());
        dto.setStartedAt(t.getStartedAt());
        dto.setCompletedAt(t.getCompletedAt());
        dto.setCreatedAt(t.getCreatedAt());
        dto.setAutoGenerated(t.getAutoGenerated());
        if (t.getRoom() != null) {
            dto.setRoomId(t.getRoom().getId());
            dto.setRoomCode(t.getRoom().getCode());
            if (t.getRoom().getBoardingHouse() != null) {
                dto.setBoardingHouseId(t.getRoom().getBoardingHouse().getId());
                dto.setBoardingHouseName(t.getRoom().getBoardingHouse().getName());
            }
        }
        if (t.getContract() != null) dto.setContractId(t.getContract().getId());
        if (t.getAssignedTo() != null) {
            dto.setAssignedToId(t.getAssignedTo().getId());
            dto.setAssignedToName(t.getAssignedTo().getFullName());
        }
        return dto;
    }
}
